name: minerva-author
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nomkl=1.0
  - numpy=1.23.3
  - pillow=9.2.0
  - flask=2.2.2
  - waitress=2.1.2
  - pydantic=1.10.9
  - flask_cors=3.0.10
  - matplotlib=3.6.1
  - tifffile=2023.7.18
  - scikit-learn=1.3.0
  - scikit-image=0.19.3
  - ome-types=0.5.0
  - Werkzeug=2.3.8
  - xsdata=23.5
  - pandas=1.5.0
  - zarr=2.13.3
  - altair=4.2.0
  - blas=*=blis  # blis build seems to avoid threading deadlocks
  - pip=22.3
  - pip:
      - openslide-python==1.2.0
      - pyinstaller==5.13
