name: minerva-author-new
channels:
  - conda-forge
dependencies:
  - python=3.13
  - blas=*=openblas
  - openai=1.78.1
  - numpy>=2.2.5
  - pillow>=11.2.1
  - flask>=3.1.1
  - waitress>=3.0.2
  - pydantic>=2.11.4
  - flask_cors>=4.0.0
  - matplotlib>=3.10.3
  - tifffile>=2025.5.10
  - scikit-learn>=1.6.1
  - scikit-image>=0.25.2
  - ome-types=0.5.0
  - Werkzeug>=3.1.3
  - xsdata==24.3.1
  - pandas>=1.5.0
  - zarr=2.18.7
  - altair>=5.5.0
  - pip>=25.1.1
  - pip:
      - openslide-python==1.4.2
