name: PyInstaller

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, windows-2025]
    runs-on: ${{ matrix.os }}
    name: Pyinstaller for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          # Install a specific version of uv as recommended by Astral.
          version: "0.12.6"
      - name: MacOS - Import codesign certificate
        if: startsWith(matrix.os, 'macos')
        uses: apple-actions/import-codesign-certs@5142e029c445c10ffc7149d172e540235a065466  # v7.0.0
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - name: Build app
        env:
          CODESIGN_IDENTITY: ${{ secrets.APPSTORE_TEAM_ID }}
        run: |
          uv run minerva-author-build-app
      - name: Set version tag (default)
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF_NAME//\//_}" >> $GITHUB_ENV
      - name: Set version tag (pull request)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          echo "VERSION=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: MacOS - Notarize App
        if: startsWith(matrix.os, 'macos')
        run: |
          cd dist
          ditto -c -k --keepParent MinervaAuthor.app MinervaAuthor.zip
          xcrun notarytool submit MinervaAuthor.zip \
            --apple-id ${{ secrets.APPSTORE_APPLE_ID }} \
            --team-id ${{ secrets.APPSTORE_TEAM_ID }} \
            --password ${{ secrets.APPSTORE_CONNECT_PASSWORD }} \
            --wait
          xcrun stapler staple MinervaAuthor.app
      - name: MacOS - Zip App
        if: startsWith(matrix.os, 'macos')
        run: |
          cd dist
          ditto -c -k --keepParent MinervaAuthor.app "../MinervaAuthor-$VERSION-mac-arm64.zip"
      - name: Windows - Zip Exe
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          cd dist
          7z a "../MinervaAuthor-$VERSION-windows-x86_64.zip" MinervaAuthor.exe
      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64  # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          name: ${{ env.tag }}
          draft: false
          prerelease: ${{ contains(github.ref, 'rc') }}
          fail_on_unmatched_files: false
          files: |
            MinervaAuthor*.zip
      - name: Upload artifacts for pull requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: minerva-author-pr${{ github.event.pull_request.number }}-${{ matrix.os }}
          path: |
            MinervaAuthor*.zip
          archive: false
          if-no-files-found: error
